[package]
name = "fair-api"
version = "0.1.0"
authors = ["Aaron Bedra <aaron@aaronbedra.com>"]
edition = "2018"

[dependencies]
actix-web = "3.1.0"
serde = { version= " 1.0.117", features = ["derive"] }
serde_json = "1.0.59"
rand = "0.7.3"
rand_distr = "0.3.0"
either = "1.6.1"